"""Visigit — Graphviz visualizations of git repository structure."""

try:
    from ._version import version as __version__
except ImportError:
    # _version.py is generated by setuptools-scm at build/editable-install
    # time; it won't exist yet in a fresh checkout that hasn't been installed.
    __version__ = "0.0.0+unknown"
